# Generated by Django 5.2.7 on 2025-11-22 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0003_quest_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Код')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pvp_battles', to='quests.quest', verbose_name='Квест')),
            ],
        ),
        migrations.CreateModel(
            name='PvpAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('failed', 'Завалено'), ('success', 'Успешно')], default='active', max_length=20, verbose_name='Статус')),
                ('given_pts', models.IntegerField(default=0, verbose_name='Полученные баллы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pvp_assignments', to='pvp.battle', verbose_name='Бой')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оппонент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'PVP задание',
                'verbose_name_plural': 'PVP задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
