# Generated by Django 5.2.7 on 2025-11-22 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0003_quest_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PvpAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_pts', models.IntegerField(default=0, verbose_name='Полученные баллы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pvp_assignments', to='quests.quest', verbose_name='Квест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'PVP задание',
                'verbose_name_plural': 'PVP задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
