# Generated by Django 5.2.7 on 2025-11-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpassignment',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='Запущено'),
        ),
    ]
