# Generated by Django 5.2.7 on 2025-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0002_pvpassignment_is_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpassignment',
            name='is_started',
        ),
        migrations.AddField(
            model_name='pvpassignment',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Готов'),
        ),
    ]
