# Generated by Django 5.2.7 on 2025-11-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0003_remove_pvpassignment_is_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvpassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('failed', 'Завалено'), ('success', 'Успешно'), ('skiped', 'Пропущено')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
