# Generated by Django 5.2.7 on 2025-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0004_alter_pvpassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpassignment',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Решение пользователя'),
        ),
    ]
