# Generated by Django 5.2.7 on 2025-11-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0005_pvpassignment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpassignment',
            name='code',
        ),
    ]
