# Generated by Django 5.2.7 on 2025-11-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0006_remove_pvpassignment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='started',
            field=models.BooleanField(default=False, verbose_name='Запущено'),
        ),
        migrations.AddField(
            model_name='pvpassignment',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Решение пользователя'),
        ),
        migrations.AlterField(
            model_name='pvpassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('ready', 'Готово'), ('completed', 'Завершено'), ('failed', 'Завалено'), ('success', 'Успешно'), ('skiped', 'Пропущено')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
