networks:
  case_db:
    driver: bridge

services:
  case_db:
    container_name: case_db
    image: postgres:17
    networks:
      - case_db
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  case_redis:
    image: redis:alpine
    container_name: case_redis
    networks:
      - case_db
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  case_celery_worker:
    build: .
    container_name: case_celery_worker
    command: celery -A battlecode worker -l info
    volumes:
      - .:/app
    networks:
      - case_db
    env_file:
      - .env
    depends_on:
      - case_redis
      - case_db

  case_celery_beat:
    build: .
    container_name: case_celery_beat
    command: celery -A battlecode beat -l info
    volumes:
      - .:/app
    networks:
      - case_db
    env_file:
      - .env
    depends_on:
      - case_redis
      - case_db

volumes:
  postgres_data:
  redis_data:
