networks:
  case-net:
    driver: bridge

services:
  case_web:
    container_name: case_web
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - django-media:/code/media
      - django-static:/code/static
    networks:
      - case-net
    env_file: ".env"
    depends_on:
      - case_db
      - case_redis

  case_db:
    container_name: case_db
    image: postgres:17-alpine
    networks:
      - case-net
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
          - postgres_data:/var/lib/postgresql/data/

  case_redis:
    image: redis:alpine
    container_name: case_redis
    networks:
      - case-net
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  case_celery_worker:
    build: .
    container_name: case_celery_worker
    restart: unless-stopped
    command: celery -A battlecode worker -l info
    volumes:
      - django-media:/code/media
    networks:
      - case-net
    env_file: ".env"
    depends_on:
      - case_redis
      - case_db

  case_celery_beat:
    build: .
    container_name: case_celery_beat
    restart: unless-stopped
    command: celery -A battlecode beat -l info 
    networks:
      - case-net
    env_file: ".env"
    depends_on:
      - case_redis
      - case_db

volumes:
  postgres_data:
  redis_data:
  django-media:
  django-static:
