# Generated by Django 5.2.7 on 2025-10-18 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[('1', 'Rookie '), ('2', 'Recruit'), ('3', 'Apprentice'), ('4', 'Journeyman'), ('5', 'Adept'), ('6', 'Specialist'), ('7', 'Expert'), ('8', 'Champion'), ('9', 'Master'), ('10', 'Grandmaster')], default=1, verbose_name='Ранг')),
                ('pts', models.IntegerField(default=0, verbose_name='Очки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('badges', models.ManyToManyField(blank=True, to='badges.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['user__username'],
            },
        ),
    ]
