# Generated by Django 5.2.7 on 2025-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pts',
            field=models.IntegerField(default=0, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(choices=[('1', 'Rookie '), ('2', 'Recruit'), ('3', 'Apprentice'), ('4', 'Journeyman'), ('5', 'Adept'), ('6', 'Specialist'), ('7', 'Expert'), ('8', 'Champion'), ('9', 'Master'), ('10', 'Grandmaster')], default=1, verbose_name='Ранг'),
        ),
    ]
