# Generated by Django 5.2.7 on 2025-10-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_course_quest_course'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='quests.course', verbose_name='Записанные курсы'),
        ),
    ]
