# Generated by Django 5.2.7 on 2025-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(choices=[('1', 'Lvl. 1 Rookie '), ('2', 'Lvl. 2 Recruit'), ('3', 'Lvl. 3 Apprentice'), ('4', 'Lvl. 4 Journeyman'), ('5', 'Lvl. 5 Adept'), ('6', 'Lvl. 6 Specialist'), ('7', 'Lvl. 7 Expert'), ('8', 'Lvl. 8 Champion'), ('9', 'Lvl. 9 Master'), ('10', 'Lvl. 10 Grandmaster')], default=1, verbose_name='Ранг'),
        ),
    ]
