# Generated by Django 5.2.7 on 2025-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursequest_course_alter_coursequest_quest'),
        ('user', '0003_alter_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_profiles', to='courses.course'),
        ),
    ]
