# Generated by Django 5.2.7 on 2025-10-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('user', '0003_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='badges.badge'),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
