# Generated by Django 5.2.7 on 2025-10-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
    ]
