# Generated by Django 5.2.7 on 2025-10-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_alter_badge_rel_quests'),
        ('user', '0004_alter_profile_badges_delete_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, to='badges.badge'),
        ),
    ]
