# Generated by Django 5.2.7 on 2025-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badge_rel_courses_alter_badge_rel_quests'),
        ('user', '0005_remove_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='badges.badge'),
        ),
    ]
