# Generated by Django 5.2.7 on 2025-10-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='rel_quests',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_badges', to='quests.quest'),
        ),
    ]
