# Generated by Django 5.2.7 on 2025-10-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
