# Generated by Django 5.2.7 on 2025-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badge_name_alter_badge_slug'),
        ('courses', '0007_alter_course_title'),
        ('quests', '0005_alter_language_name_alter_quest_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='rel_courses',
            field=models.ManyToManyField(blank=True, related_name='badges', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='rel_quests',
            field=models.ManyToManyField(blank=True, related_name='badges', to='quests.quest'),
        ),
    ]
