# Generated by Django 5.2.7 on 2025-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badge_rel_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
