# Generated by Django 5.2.7 on 2025-10-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_badge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
