# Generated by Django 5.2.7 on 2025-10-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_badge_description'),
        ('quests', '0002_language_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='rel_quests',
            field=models.ManyToManyField(blank=True, null=True, to='quests.quest'),
        ),
    ]
