# Generated by Django 5.2.7 on 2025-10-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quests', to='courses.course')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quests', to='quests.quest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'quest')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='quests',
            field=models.ManyToManyField(related_name='courses', through='courses.CourseQuest', to='quests.quest'),
        ),
    ]
