# Generated by Django 5.2.7 on 2025-10-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quests', '0003_alter_quest_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequest',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='course',
            name='quests',
            field=models.ManyToManyField(related_name='courses', through='courses.CourseQuest', to='quests.quest'),
        ),
        migrations.AlterField(
            model_name='coursequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursequest',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coursequest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.quest'),
        ),
        migrations.AlterUniqueTogether(
            name='coursequest',
            unique_together={('course', 'quest')},
        ),
    ]
