# Generated by Django 5.2.7 on 2025-10-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursequest_options_course_quests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequest',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
