# Generated by Django 5.2.7 on 2025-10-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_slug'),
        ('quests', '0004_alter_quest_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quests', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursequest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quests', to='quests.quest'),
        ),
    ]
