# Generated by Django 5.2.7 on 2025-11-13 10:23

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestReviewChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Чек-лист ревью квеста',
                'verbose_name_plural': 'Чек-листы ревью квеста',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('value', models.IntegerField(default=0, verbose_name='Вес навыка')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание пункта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='quests.questreviewchecklist', verbose_name='Чек-лист Ревью')),
            ],
            options={
                'verbose_name': 'Элемент чеклиста',
                'verbose_name_plural': 'Элементы чеклиста',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard🔥')], max_length=20, verbose_name='Сложность')),
                ('base_pts', models.IntegerField(default=10, verbose_name='Баллы за победу (без множителя)')),
                ('penalty', models.PositiveIntegerField(default=0, verbose_name='Штраф за проигрыш')),
                ('work_time', models.IntegerField(default=3, verbose_name='Время работы')),
                ('task', models.TextField(verbose_name='Задача')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quests', to='quests.language', verbose_name='Язык')),
                ('checklist', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='quests.questreviewchecklist', verbose_name='Чек-лист ревью квеста')),
                ('skills', models.ManyToManyField(related_name='quests', to='quests.skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'ordering': ['-created_at'],
            },
        ),
    ]
