# Generated by Django 5.2.7 on 2025-10-10 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(blank=True)),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Задача')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Квест - задача',
                'verbose_name_plural': 'Квесты - задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestReviewChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Чек-лист ревью квеста',
                'verbose_name_plural': 'Чек-листы ревью квеста',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(blank=True)),
                ('value', models.IntegerField(default=0, verbose_name='Вес навыка')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.CharField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard🔥')], max_length=20, verbose_name='Сложность')),
                ('base_pts', models.IntegerField(default=10, verbose_name='Баллы за победу (без множителя)')),
                ('penalty', models.IntegerField(default=0, verbose_name='Штраф за проигрыш')),
                ('work_time', models.IntegerField(default=3, verbose_name='Время работы')),
                ('check_time', models.IntegerField(default=3, verbose_name='Время проверки')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quests', to='quests.language', verbose_name='Язык')),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quests.questdetail', verbose_name='Задачи')),
                ('checklist', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='quests.questreviewchecklist', verbose_name='Чек-лист ревью квеста')),
                ('skills', models.ManyToManyField(to='quests.skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('reviews', models.IntegerField(default=0, verbose_name='Количество проверок')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('failed', 'Завалено')], default='active', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.quest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'Взятое задание',
                'verbose_name_plural': 'Взятые задания',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание пункта')),
                ('is_working', models.BooleanField(default=False, verbose_name='Работает?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='quests.questreviewchecklist', verbose_name='Ревью')),
            ],
            options={
                'verbose_name': 'Элемент чеклиста',
                'verbose_name_plural': 'Элементы чеклиста',
                'ordering': ['-created_at'],
            },
        ),
    ]
