# Generated by Django 5.2.7 on 2025-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.RemoveField(
            model_name='quest',
            name='pts',
        ),
        migrations.AddField(
            model_name='quest',
            name='base_pts',
            field=models.IntegerField(default=10, verbose_name='Баллы за победу (без множителя)'),
        ),
    ]
