# Generated by Django 5.2.7 on 2025-10-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quests.questdetail', verbose_name='Задачи'),
        ),
    ]
