# Generated by Django 5.2.7 on 2025-11-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='checklist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quest', to='quests.questreviewchecklist', verbose_name='Чек-лист ревью квеста'),
        ),
    ]
