# Generated by Django 5.2.7 on 2025-10-11 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.CharField(blank=True, unique=True)),
                ('base_pts', models.IntegerField(default=10, verbose_name='Баллы за прохождение курса')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard🔥')], max_length=20, verbose_name='Сложность')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quests', models.ManyToManyField(blank=True, related_name='courses_for_quest', to='quests.quest', verbose_name='Квесты')),
                ('skills', models.ManyToManyField(blank=True, to='quests.skill', verbose_name='Прокачиваемые навыки')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests_in_course', to='quests.course', verbose_name='Курс'),
        ),
    ]
