# Generated by Django 5.2.7 on 2025-10-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='is_working',
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='quests.questreviewchecklist', verbose_name='Чек-лист Ревью'),
        ),
    ]
