# Generated by Django 5.2.7 on 2025-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='Количество проверок'),
        ),
    ]
