# Generated by Django 5.2.7 on 2025-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
