# Generated by Django 5.2.7 on 2025-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_remove_checklistitem_is_working_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='slug',
            field=models.CharField(blank=True, null=True),
        ),
    ]
