# Generated by Django 5.2.7 on 2025-10-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_remove_quest_check_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
    ]
