# Generated by Django 5.2.7 on 2025-10-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_course_quest_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quests',
            field=models.ManyToManyField(blank=True, related_name='courses_for_course', to='quests.quest', verbose_name='Квесты'),
        ),
    ]
