# Generated by Django 5.2.7 on 2025-10-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_language_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Цвет текста'),
        ),
    ]
