# Generated by Django 5.2.7 on 2025-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
