# Generated by Django 5.2.7 on 2025-11-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_alter_quest_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='task_type',
            field=models.CharField(choices=[('task', 'Задача'), ('pvp', 'PVP')], default='task', max_length=20, verbose_name='Тип задания'),
        ),
    ]
