# Generated by Django 5.2.7 on 2025-10-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_language_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='text_color',
        ),
    ]
