# Generated by Django 5.2.7 on 2025-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_alter_quest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='skills',
            field=models.ManyToManyField(related_name='quests', to='quests.skill', verbose_name='Навыки'),
        ),
    ]
