# Generated by Django 5.2.7 on 2025-10-29 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_pts', models.IntegerField(default=0, verbose_name='Полученные баллы')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('failed', 'Завалено'), ('success', 'Успешно')], default='active', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quests.quest', verbose_name='Квест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взятое задание',
                'verbose_name_plural': 'Взятые задания',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('failed', 'Заваленный'), ('success', 'Завершенный')], default='active', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по курсу',
                'verbose_name_plural': 'Прогресс по курсам',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_tasks', models.IntegerField(default=0, verbose_name='Завершено заданий')),
                ('grade', models.IntegerField(default=1, verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('give_pts', models.IntegerField(default=0, verbose_name='Баллы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peer_review.assignment', verbose_name='Квест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ревью',
                'verbose_name_plural': 'Ревью',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.BooleanField(default=False, verbose_name='Выполнено (Да/Нет)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quests.checklistitem', verbose_name='Пункт чек-листа')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='peer_review.review', verbose_name='Ревью')),
            ],
            options={
                'verbose_name': 'Ответ на пункт чек-листа',
                'verbose_name_plural': 'Ответы на пункты чек-листа',
                'unique_together': {('review', 'checklist_item')},
            },
        ),
    ]
