# Generated by Django 5.2.7 on 2025-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='given_pts',
            field=models.IntegerField(default=0, verbose_name='Полученные баллы'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('failed', 'Завалено'), ('success', 'Успешно')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
