# Generated by Django 5.2.7 on 2025-10-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
        ('quests', '0004_alter_quest_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quests.quest', verbose_name='Квест'),
        ),
    ]
