# Generated by Django 5.2.7 on 2025-10-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
        ('quests', '0002_remove_checklistitem_is_working_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='completed_tasks',
            field=models.IntegerField(default=0, verbose_name='Завершено заданий'),
        ),
        migrations.AddField(
            model_name='review',
            name='give_pts',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.CreateModel(
            name='ReviewChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.BooleanField(default=False, verbose_name='Выполнено (Да/Нет)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quests.checklistitem', verbose_name='Пункт чек-листа')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='peer_review.review', verbose_name='Ревью')),
            ],
            options={
                'verbose_name': 'Ответ на пункт чек-листа',
                'verbose_name_plural': 'Ответы на пункты чек-листа',
                'unique_together': {('review', 'checklist_item')},
            },
        ),
    ]
