# Generated by Django 5.2.7 on 2025-10-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0003_courseprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprogress',
            old_name='completed',
            new_name='status',
        ),
    ]
