# Generated by Django 5.2.7 on 2025-10-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0004_rename_completed_courseprogress_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'verbose_name': 'Прогресс по курсу', 'verbose_name_plural': 'Прогресс по курсам'},
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together=set(),
        ),
    ]
