# Generated by Django 5.2.7 on 2025-10-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0005_alter_courseprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Прогресс по курсу', 'verbose_name_plural': 'Прогресс по курсам'},
        ),
    ]
