name: main

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

env:
  DB_USER: ${{ secrets.POSTGRES_USER }}
  DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  DB_NAME: ${{ secrets.POSTGRES_DB }}
  DB_PORT: ${{ secrets.DB_PORT }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12

    steps:
      - uses: actions/checkout@v5

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          libpq-dev \
          gcc

      - name: 📦 Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: 📦 Install dependencies
        run: uv sync

      - name: 🧪 Lint with Ruff
        run: uv run ruff check battlecode

      - name: 🐳 Build and run containers
        run: docker-compose up -d --build

      - name: 🧪 Run tests
        run: |
          sleep 10
          docker-compose exec -T case_web uv run python battlecode/manage.py test

      - name: 🧹 Stop containers
        if: always()
        run: docker-compose down

